### ISSUE TITLE
Use an OSI-approved license

### ISSUE THREAD

**Issue by andreilg** [MarcelGarus/glados#18]
The license listed for this repository isn't recognized as an OSI-approved license on GitHub or on pub.dev. 

Updating this license to an OSI-approved one like BSD-3 Clause would make users such as myself much more comfortable with using this package and would also increase your pub points on pub.dev (it is currently penalized [10 points](https://pub.dev/packages/glados/score) because of this issue).

**Comment by MarcelGarus** [comment]
This is fixed in 1.1.5.
Thanks for noticing!
