### ISSUE TITLE
Support analyzer 5

### ISSUE THREAD

**Issue by tjarvstrand** [MarcelGarus/glados#20]
Unfortunately, Glados is currently incompatible with the most recent version of many libraries

**Comment by MarcelGarus** [comment]
Oops, thanks for the heads-up. I'm currently not using Glados myself and I'm on vacation until the beginning of October, but I'll put it on my todo list for then.

**Comment by MarcelGarus** [comment]
Thanks for your patience!
This is fixed now and published as 1.1.6.

**Comment by tjarvstrand** [comment]
Thanks!
