### ISSUE TITLE
Consider dropping the '(testing 100 inputs)' suffix in test description

### ISSUE THREAD

**Issue by kotertom** [MarcelGarus/glados#28]
Hi! The title says it all, but here's the long story. First of all, thank you very much for writing this neat package :) I encountered it completely by chance but it got me into exploring different approaches to testing code and essentially made me appreciate writing tests instead of viewing them as a mostly tedious, repetitive chore.

I encountered one quality of life issue that's been bugging me for the past few days: I use vscode with the [dart-code](https://dartcode.org/) extension and the editor gets all confused when trying to launch a single Glados test using vscode's gutter button and code lens (see screenshot). That's because it searches for the test by name and fails with the message below.

```
// output for a test defined as `Glados(any.int).test('description goes here', (_) {});`
No tests match regular expression "^description goes here( \(variant: .*\))?$".
Exited (1)
```

<img width="224" alt="image" src="https://github.com/MarcelGarus/glados/assets/9551524/0dba1db0-c73d-4c61-bbd2-6e93f14a99f6">

The extension expects to match the name exactly, with an optional ` (variant: <whatever>)` suffix, while Glados appends a ` (testing $numRuns inputs)` string. I'm not sure if it would even be possible for the extension to resolve this kind of a dynamic name.

So, here's my request: would it be ok to drop the '(testing x inputs)' suffix? Instead, the test could print this information.

The [isTest annotation docs](https://pub.dev/documentation/meta/latest/meta/isTest-constant.html) also sound to me as if the test description was supposed to be passed around unmodified.

> Used to annotate a test framework function that runs a single test.
>
> Tools, such as IDEs, can show invocations of such function in a file structure view to help the user navigating in large test files.
>
> The first parameter of the function must be the description of the test.

I'm not sure how this affects other IDEs, though, since I mainly use vscode.

What do you think? Would you mind making this change? If it's fine I could prepare a pull request.

**Comment by JonasWanke** [comment]
@kotertom As a workaround, there's a new setting that got introduced in Dart Code [v3.64.0 (released on 2023-05-10)](https://dartcode.org/releases/#v3640-2023-05-10): Setting “Dart: Test Invocation Mode” to “line” makes it work with Glados (see https://github.com/Dart-Code/Dart-Code/issues/4099). In the JSON config for VS Code, the setting looks like this: `"dart.testInvocationMode": "line"`

**Comment by kotertom** [comment]
@JonasWanke thanks for taking the time and answering so soon 😄 Sorry, I should've searched the Dart-Code repo more thoroughly for similar issues. I actually found the setting before posting the issue but it somehow failed to work in my project. Perhaps my test package's version is too outdated, looking at this sentence in the setting's docs.

> https://dartcode.org/docs/settings/#darttestinvocationmode
>
> name is compatible with older versions of package:test but cannot handle some complex/dynamic test names.

Anyway, I'll poke around with the setting a bit more and try it on a fresh project, which I should've done in the first place. Thanks again 😅 I'll close the issue since no one else seems to be having problems with the Dart-Code + Glados integration, so this is most likely something on my end.

**Comment by kotertom** [comment]
Just a tiny update for anyone who might stumble upon this issue: the outdated flutter/test version was in fact the issue. I've dug up these two lines that define the minimum required sdk versions:

- flutter 3.10.0 https://github.com/Dart-Code/Dart-Code/pull/4487/files#diff-99f109eb4eedc6b106f4e32fbff1f308874c11cb8e5bc29dd5cc42a1171175dcR30
- package:test 1.23.1 https://github.com/Dart-Code/Dart-Code/pull/4487/files#diff-4cf348a959d9040e08ce3cb1e8116189f145e5f259dcb345bb101cf965217198R13

The project I had the issue with uses an earlier flutter version (3.7). The setting works well in newer projects 😄 I wasn't aware this is such a recent development. For the older project as a workaround I just run an entire test group or file, or use the CLI if I really want to run just that one specific test.
